name: Release

# Push events to matching v*, i.e. v1.0, v20.15.10
on:
  push:
    tags:
    - 'v*'

jobs:
  check:
    timeout-minutes: 30
    name: Check Signed Tag
    runs-on: ubuntu-20.04
    outputs:
      stringver: ${{ steps.contentrel.outputs.stringver }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          path: src/github.com/auxon/modality-trace-recorder-plugin

      - name: Check signature
        run: |
          RELEASE_TAG=${{ github.ref }}
          RELEASE_TAG="${RELEASE_TAG#refs/tags/}"
          TAGCHECK=$(git tag -v ${RELEASE_TAG} 2>&1 >/dev/null) ||
          echo "${TAGCHECK}" | grep -q "error" && {
              echo "::error::tag ${RELEASE_TAG} is not a signed tag. Failing release process."
              exit 1
          } || {
              echo "Tag ${RELEASE_TAG} is signed."
              exit 0
          }
        working-directory: src/github.com/auxon/modality-trace-recorder-plugin

  package:
    name: Build Release Package
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    needs: [check]
    steps:
      - name: Print version
        run: |
          RELEASE_TAG=${{ github.ref }}
          RELEASE_TAG="${RELEASE_TAG#refs/tags/}"
          RELEASE_VERSION="${RELEASE_TAG#v}"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Release tag: $RELEASE_TAG"
          echo "Release version: $RELEASE_VERSION"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libusb-1.0-0-dev libftdi1-dev libudev-dev

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Fetch dependencies
        uses: actions-rs/cargo@v1
        with:
          command: fetch

      - name: Build release binaries
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Create github release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          name: Release ${{ env.RELEASE_VERSION }}
          files: |
            target/release/modality-trace-recorder-importer
            target/release/modality-trace-recorder-tcp-collector
            target/release/modality-trace-recorder-itm-collector
